language: cpp
sudo: required
dist: bionic
addons:
  apt:
    packages:
      - gfortran
      - mpich
      - libmpich-dev
      - libhdf5-mpich-dev
      - liblapack-dev
    config:
      retries: true
cache:
  directories:
    - $HOME/endfb71_hdf5
env:
  global:
    - HDF5_ROOT=/usr
    - OMP_NUM_THREADS=2
    - OPENMC_CROSS_SECTIONS=$HOME/endfb71_hdf5/cross_sections.xml
matrix:
  include:
    - env: MODE="openmc_nek5000"
    - env: MODE="openmc_nekrs"
    - env: MODE="openmc_heat_surrogate"

before_install:
  - bash ci/patch_singlerod_input.sh

install:
  - bash ci/cmake_singlerod.sh
  - bash ci/build_singlerod.sh
  - bash ci/build_unittests.sh

before_script:
  - bash ci/download_xs.sh
  - bash ci/unzip_singlerod_statefile.sh

script:
  - bash ci/singlerod_matrix.sh
  - bash ci/test_unittests.sh
